[chore] enable windows container builds on CI (#1154)
add core arm64

update package tests to new package naming scheme

update snapshot version config

remove arch from k8s since its not needed

Revert "refactoring"

This reverts commit 590644c001c428fcfbe3a0b7383c2b7bc43fc54d.

change variable back

add prev version to correct step

add needs

copy over prev tag job

refactoring

dont run docker tests on windows arm

minor changes

replace shorthand with longer version

try again with windows 2022 runner

build local windows image for 2025

try mounting folder on windows

try double forward slashes

Revert "try again"

This reverts commit ccb23f03

remove double backslashes

try with redirection after log file name

try again

fix log file name

try backticks

try with PS

try again on bash for windows

try more things

revert prep changes again

try output redirection again

revert cmd option newline

revert some variable prep changes

fix logging

try with newline

try shorthand

and again

try again with PS

try running separate docker run cmd for windows

more default shells

Revert "more default shells"

This reverts commit 55ba0ae8069a528753140268417d2a14e06d4983.

set bash as default shell

see if explicitely splitting args works

one step closer

fix more quotes

add missing quote

remove dash

set tag env var correctly

use runner_temp dir to be OS independent

fix docker cmd

set windows dockerfile

try building on windows without actions and buildx

enable buildx also on windows

build container images for testing

try to go back to single version without specific OS

add back os conditional

run variable output on bash

more debugging

try without quotes

debugging

try again without backslashes

combine linux and windows var prep

try to set variables separately for windows

also run echo step

set variables also on windows

try running docker tests on windows runner

try to fix version numbers for msi installers

fix job name

try fixing otelcol core wxs version templating

try again to just build MSIs

just run docker tests on linux runners

simplify variable prep step

try running more steps on windows

enable windows builds on other distros

disable qemu on windows docker-tests job

disable msi builds on snapshot builds

remove wixl on windows

remove unneeded conditional

revert removal of wixl

Revert "revert changes to windows runner"

This reverts commit 6ce5fa64fa0ea5c7e6f5f917cd13b0b956f15972.

Revert "disable windows container building skips"

This reverts commit cf2f10ded7b8e78db426145b6a7ca64f28930bcf.

Revert "remove windows skips from goreleaser cfg"

This reverts commit b6f49184dc290ad42f854a262a35c3ae8ed98020.

Revert "only build windows containers"

This reverts commit 69c606c8027da7c36f5a7e21acb8656b88c68932.

only build windows containers

remove windows skips from goreleaser cfg

disable windows container building skips

revert changes to windows runner

more skipping

remove wixl step

diff --git a/.github/workflows/base-ci-goreleaser.yaml b/.github/workflows/base-ci-goreleaser.yaml
--- a/.github/workflows/base-ci-goreleaser.yaml
+++ b/.github/workflows/base-ci-goreleaser.yaml
@@ -95,17 +95,19 @@ jobs:
           fetch-depth: 0
 
       - name: Setup QEMU
+        if: runner.os != 'Windows'
         uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
         with:
           platforms: arm64,ppc64le,linux/arm/v7,s390x,riscv64
 
       - name: Setup wixl # Required to build MSI packages for Windows
-        if: ${{ matrix.GOOS == 'windows' && ( matrix.GOARCH == '386' || matrix.GOARCH == 'amd64') }}
+        if: runner.os != 'Windows'
         run: |
           sudo apt-get update
           sudo apt-get install -y wixl
 
       - name: Setup Docker Buildx
+        if: runner.os != 'Windows'
         uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
 
       - name: Setup Go
@@ -186,7 +188,7 @@ jobs:
         run: mv distributions/otelcol-contrib/dist/**/* distributions/otelcol-contrib/artifacts/
 
       - name: Show built or downloaded content
-        if: inputs.distribution == 'otelcol-contrib'
+        if: inputs.distribution == 'otelcol-contrib' && runner.os != 'Windows'
         run: ls -laR distributions/otelcol-contrib/artifacts
 
       - name: Run GoReleaser for ${{ inputs.distribution }}
@@ -212,7 +214,7 @@ jobs:
         run: cat ./distributions/${{ inputs.distribution }}/dist/**/metadata.json
 
       - name: Print dist folder contents
-        if: always()
+        if: always() && runner.os != 'Windows'
         run: ls -laR ./distributions/${{ inputs.distribution }}/dist
 
       - name: Upload linux service packages
@@ -232,53 +234,66 @@ jobs:
           if-no-files-found: error
 
       - name: Prepare variables
-        if: matrix.GOOS == 'linux'
+        if: matrix.GOOS == 'linux' || matrix.GOOS == 'windows'
         id: prep
+        shell: bash
         run: |
           # Find version number and types of built artifacts
-          echo "version=$(cat ./distributions/${{ inputs.distribution }}/dist/**/metadata.json | jq -r '.version')" >> "$GITHUB_OUTPUT"
-          echo "types=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq '[.[].type]' | tr -d '\n' )" >> "$GITHUB_OUTPUT"
-
-          # Find GOOS and GOARCH
-          os=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq -r '.[] | select(.name | contains(".tar.gz")) | .goos')
-          arch=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq -r '.[] | select(.name | contains(".tar.gz")) | .goarch')
-          echo "arch=$os-$arch" >> "$GITHUB_OUTPUT"
-
+          version=$(cat ./distributions/${{ inputs.distribution }}/dist/**/metadata.json | jq -r '.version')
+          arch="${{ matrix.GOOS }}-${{ matrix.GOARCH }}"
+          
+          echo "version=$version" >> $GITHUB_OUTPUT
+          echo "arch=$arch" >> $GITHUB_OUTPUT
+          echo "types=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq '[.[].type]' | tr -d '\n' )" >> $GITHUB_OUTPUT
+          
           # Find binary path
-          echo "binary-path=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq -r 'map(select(any(.type; contains("Binary")))) | .[].path' )" >> "$GITHUB_OUTPUT"
+          echo "binarypath=$(cat ./distributions/${{ inputs.distribution }}/dist/**/artifacts.json | jq -r 'map(select(any(.type; contains("Binary")))) | .[].path' )" >> "$GITHUB_OUTPUT"
+          
+          echo "TAG=${{ inputs.distribution }}:$version-$arch" >> $GITHUB_ENV
+
 
       - name: Print version and target
-        if: matrix.GOOS == 'linux'
+        if: matrix.GOOS == 'linux' || matrix.GOOS == 'windows'
         run: |
           echo 'Version: ${{ steps.prep.outputs.version }}'
           echo 'Types: ${{ steps.prep.outputs.types }}'
           echo 'Arch: ${{ steps.prep.outputs.arch }}'
+          echo 'Binary path: ${{ steps.prep.outputs.binarypath }}'
           echo 'Images?: ${{ steps.prep.outputs.container-images }}'
+          echo 'Image tag: ${{ env.TAG }}'
 
       - name: Copy binary to distro root folder
-        if: matrix.GOOS == 'linux'
-        run: cp ./distributions/${{ inputs.distribution }}/${{ steps.prep.outputs.binary-path }} ./distributions/${{ inputs.distribution }}
+        if: matrix.GOOS == 'linux' || matrix.GOOS == 'windows'
+        run: cp ./distributions/${{ inputs.distribution }}/${{ steps.prep.outputs.binarypath }} ./distributions/${{ inputs.distribution }}
 
-      - name: Build container images locally
+      - name: Build container images locally (Linux)
         if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
         uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
         with:
           context: ./distributions/${{ inputs.distribution }}
           push: false
           load: true
-          tags: ${{ inputs.distribution }}:${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }}
+          tags: ${{ env.TAG }}
+
+      - name: Build container images locally (Windows)
+        if: matrix.GOOS == 'windows' && contains(steps.prep.outputs.types, 'Docker Image')
+        run: |
+          docker build -f ./distributions/${{ inputs.distribution }}/Windows.dockerfile `
+            -t ${{ env.TAG }} `
+            --build-arg WIN_VERSION=2022 `
+            ./distributions/${{ inputs.distribution }}/
 
       - name: Export container image to tarball
-        if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
+        if: (matrix.GOOS == 'linux' || matrix.GOOS == 'windows') && contains(steps.prep.outputs.types, 'Docker Image')
         run: |
-          docker save ${{ inputs.distribution }}:${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }} > /tmp/${{ inputs.distribution }}.tar
+          docker save ${{ env.TAG }} > ${{ runner.temp }}/${{ inputs.distribution }}.tar
 
       - name: Upload container image artifact
-        if: matrix.GOOS == 'linux' && contains(steps.prep.outputs.types, 'Docker Image')
+        if: (matrix.GOOS == 'linux' || matrix.GOOS == 'windows') && contains(steps.prep.outputs.types, 'Docker Image')
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
           name: ${{ inputs.distribution }}-image-${{ steps.prep.outputs.version }}-${{ steps.prep.outputs.arch }}
-          path: /tmp/${{ inputs.distribution }}.tar
+          path: ${{ runner.temp }}/${{ inputs.distribution }}.tar
           retention-days: 7
 
   docker-tests:
@@ -291,12 +306,18 @@ jobs:
         exclude:
           - GOOS: darwin
           - GOOS: windows
+            GOARCH: "386"
+          - GOOS: windows
+            GOARCH: arm64
     runs-on: ${{ inputs.runner_os }}
+    env:
+      TAG: ${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
     steps:
       - name: Checkout
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
 
       - name: Setup QEMU
+        if: runner.os != 'Windows'
         uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
         with:
           platforms: arm64,ppc64le,linux/arm/v7,s390x,riscv64
@@ -304,22 +325,23 @@ jobs:
       - name: Download container image artifact
         uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
         with:
-          name: ${{ inputs.distribution }}-image-${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
+          name: ${{ inputs.distribution }}-image-${{ env.TAG }}
 
       - name: Load image into docker
         run: |
           docker image load --input ./${{ inputs.distribution }}.tar
           docker image ls
-          docker image inspect ${{ inputs.distribution }}:${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }}
+          docker image inspect ${{ inputs.distribution }}:${{ env.TAG }}
 
-      - name: Run container image
+      - name: Run container image (Linux)
+        if: matrix.GOOS == 'linux'
         run: |
           echo "Running container..."
           docker run --name ${{ inputs.distribution }} \
             -d \
             ${{ inputs.docker_run_options }} \
             -v ${PWD}/tests/docker-tests/${{ inputs.config_file }}:/config.yaml \
-            ${{ inputs.distribution }}:${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }} \
+            ${{ inputs.distribution }}:${{ env.TAG }} \
             ${{ inputs.otelcol_run_options }} --config /config.yaml
           echo "docker ps:"
           echo ""
@@ -327,7 +349,7 @@ jobs:
           echo "Sleeping for a bit..."
           sleep 10
           echo "Checking logs for correct startup..."
-          docker logs ${{ inputs.distribution }} >& docker-logs-${{ inputs.distribution }}.log
+          docker logs ${{ inputs.distribution }} &>docker-logs-${{ inputs.distribution }}.log
           if cat docker-logs-${{ inputs.distribution }}.log | grep "Everything is ready."; then
             echo "${{ inputs.distribution }} started up correctly"
           else
@@ -338,12 +360,40 @@ jobs:
             exit 1
           fi
 
+      - name: Run container image (Windows)
+        if: matrix.GOOS == 'windows'
+        run: |
+          echo "Running container..."
+          docker run --name ${{ inputs.distribution }} `
+            -d `
+            ${{ inputs.docker_run_options }} `
+            -v ${PWD}\tests\docker-tests:C:\config `
+            ${{ inputs.distribution }}:${{ env.TAG }} `
+            --config C:\config\${{ inputs.config_file }} `
+            ${{ inputs.otelcol_run_options }}
+          echo "docker ps:"
+          echo ""
+          docker ps
+          echo "Sleeping for a bit..."
+          sleep 10
+          echo "Checking logs for correct startup..."
+          docker logs ${{ inputs.distribution }} *> "docker-logs-${{ inputs.distribution }}.log"
+          if (Get-Content docker-logs-${{ inputs.distribution }}.log | Select-String -Pattern "Everything is ready.") {
+            echo "${{ inputs.distribution }} started up correctly"
+          } else {
+            echo "${{ inputs.distribution }} failed to start"
+            echo "Printing container logs below..."
+            echo ""
+            Get-Content docker-logs-${{ inputs.distribution }}.log
+            exit 1
+          }
+
       - name: Run golden tests
         if: matrix.GOOS == 'linux' && matrix.GOARCH == 'amd64' && inputs.distribution == 'otelcol-contrib'
         run: |
           echo "Running golden tests..."
           cd tests/golden
-          MY_UID="$(id -u)" MY_GID="$(id -g)" IMG=${{ inputs.distribution }}:${{ needs.check-goreleaser.outputs.version }}-${{ matrix.GOOS }}-${{ matrix.GOARCH }} docker compose up -d --wait
+          MY_UID="$(id -u)" MY_GID="$(id -g)" IMG=${{ inputs.distribution }}:${{ env.TAG }} docker compose up -d --wait
           exit_code=$(docker wait golden)
           docker logs golden
           if [ "$exit_code" -ne 0 ]; then
